### ISSUE TITLE
$SYS/# messages are in #

### ISSUE THREAD

**Issue by jpmens** [erlio/vmq_systree#2]
I note `$SYS/#` messages (e.g. `$SYS/VerneMQ@127.0.0.1/memory/ets`) are sent to subscribers who subscribe to `#`. I think these should be "hidden" unless the `$SYS/#` topic branch is subscribed to expliicitly.

FWIW, this is how Mosquitto handles it.

**Comment by jpmens** [comment]
As pointed out by @ralight this behaviour fails [the standard](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108)

**Comment by dergraf** [comment]
duplicate #14

**Comment by dergraf** [comment]
fixed in newest vmq_server
